// Generated by scripts/export_intent_demo_schema.py; proposed demo v0.1.
// These are distinct from existing Core contracts. Do not hand-edit.

export type BehaviorEvent = {
  event_id: string
  task_id: string
  step_index: number
  actor: string
  source_type: "user" | "agent" | "retrieval" | "tool" | "memory" | "system"
  source_ref: string
  subgoal: string
  tool: string
  action: string
  args_digest: string
  target: string
  risk_flags: Array<string>
  timestamp: string
}

export type CorrectionPlan = {
  plan_id: string
  base_contract_version: number
  contaminated_refs: Array<string>
  proposed_actions: Array<Record<string, unknown>>
  added_scope: Array<string>
  confirmation_required: boolean
  retry_budget: number
  status: "PROPOSED" | "EXECUTED" | "REJECTED"
}

export type DecisionResult = {
  decision_id: string
  decision: "ALLOW" | "BLOCK" | "CLARIFY" | "REPLAN"
  risk_score: number
  trigger_dimensions: Array<string>
  evidence_refs: Array<string>
  reason_code: string
  policy_version: string
  detector_version: string
  expires_at: string
}

export type EffectCheck = {
  effect_id: string
  request_id: string
  tool: string
  normalized_target: string
  before_digest: string
  after_digest: string
  side_effect_ref: string | null
  status: "UNCHANGED" | "APPLIED" | "FAILED" | "MISMATCH"
}

export type IntentSpec = {
  intent_id: string
  task_id: string
  goal: string
  scope: Array<string>
  allowed_actions: Array<string>
  forbidden_actions: Array<string>
  success_criteria: Array<string>
  source_refs: Array<string>
  version: number
  confirmed_by: string | null
  confirmed_at: string | null
}

export type TaskContract = {
  contract_id: string
  contract_version: number
  intent_ref: string
  resources: Array<string>
  tools: Array<string>
  permissions: Record<string, string>
  completion_conditions: Array<string>
  parent_version: number | null
  status: "DRAFT" | "CONFIRMED" | "SUPERSEDED"
  digest: string
}
