// Generated by scripts/export_core_event_contracts.py from P2 OpenAPI schemas.
// Do not edit by hand. Runtime validation remains on the service boundary.

export type BehaviorEvent = {
  schema_version?: "1.0"
  event_id: string
  sequence: number
  task_id: string
  parent_event_id: string | null
  type: string
  actor: string
  source_ref: string
  object_digest: string | null
  state: string
  decision: GatewayDecisionType | null
  result_digest: string | null
  occurred_at: string
  request_id?: string | null
  reason_code?: GatewayReasonCode | null
  evidence_refs?: Array<string>
  prepared_effect_id?: string | null
  effect_descriptor_digest?: string | null
  result_commitment?: string | null
  commit_epoch?: number | null
  execution_receipt_id?: string | null
  compliance_proof_ref?: string | null
}

export type ConfirmationPolicyV1 = {
  required_actions?: Array<string>
  required_effect_classes?: Array<EffectClass>
}

export type ContractPermissionRule = {
  tool?: string
  action: string
  resource?: string
  effect?: string
}

export type EffectClass = "READ" | "WRITE" | "DELETE" | "MEMORY" | "NETWORK" | "PROCESS" | "OTHER"

export type EffectivePermission = {
  allowed?: Array<PermissionGrant>
  denied?: Array<PermissionGrant>
  constraints?: Record<string, unknown>
  matched_sources?: Array<string>
  conflict_reason?: string | null
  conflict_code?: GatewayReasonCode | null
  requires_confirmation?: boolean
}

export type GatewayDecision = {
  decision: GatewayDecisionType
  reason_code: GatewayReasonCode
  evidence_refs?: Array<string>
  versions?: Record<string, number | string>
  confirmation_id?: string | null
}

export type GatewayDecisionType = "ALLOW" | "DENY" | "REQUIRE_CONFIRMATION" | "REQUIRE_REPLAN"

export type GatewayReasonCode = "ALLOWED" | "USER_DENY" | "OUT_OF_CONTRACT" | "SKILL_LIMIT" | "SYSTEM_DENY" | "RESOURCE_MISMATCH" | "VERSION_STALE" | "CONFIRMATION_REQUIRED" | "CHECK_UNAVAILABLE" | "ADAPTER_BYPASS" | "SIGNATURE_INVALID"

export type GrantEffect = "ALLOW" | "DENY"

export type GrantScope = "GLOBAL" | "SESSION" | "TASK" | "ONE_SHOT"

export type PermissionGrant = {
  subject: string
  skill: string
  tool: string
  action: string
  resource: string
  effect: GrantEffect
  scope: GrantScope
  expires_at?: string | null
  source: string
  limits?: Record<string, number | number>
  scope_ref?: string | null
}

export type TaskContractV2 = {
  contract_id: string
  session_id: string
  task_id: string
  user_id: string
  version: number
  goals: Array<string>
  completion_criteria?: Array<string>
  allowed?: Array<ContractPermissionRule>
  denied?: Array<ContractPermissionRule>
  limits?: Record<string, number | number | string | boolean>
  confirmation?: ConfirmationPolicyV1
  policy_version: string
  tool_manifest_digest: string
  parent_digest?: string | null
  prepared_effect_id?: string | null
  effect_descriptor_digest?: string | null
  result_commitment?: string | null
  commit_epoch?: number | null
  execution_receipt_id?: string | null
  compliance_proof_ref?: string | null
}
