"""Generate member 4 demo JSON Schema and TS from the same proposed models."""

import argparse
import json
from pathlib import Path

from ra_agent.intent_demo.contracts import IntentDemoSchema
from scripts.export_core_event_contracts import typescript

ROOT = Path(__file__).resolve().parents[1]


def artifacts() -> dict[Path, str]:
    schema = IntentDemoSchema.model_json_schema()
    ts = "// Generated by scripts/export_intent_demo_schema.py; proposed demo v0.1.\n"
    ts += "// These are distinct from existing Core contracts. Do not hand-edit.\n\n"
    ts += (
        "\n\n".join(
            f"export type {name} = {typescript(definition)}"
            for name, definition in schema["$defs"].items()
        )
        + "\n"
    )
    return {
        ROOT / "docs/contracts/intent-demo-v0.1.schema.json": json.dumps(
            schema, ensure_ascii=False, indent=2
        )
        + "\n",
        ROOT / "frontend/src/features/intent/generated.ts": ts,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, value in artifacts().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != value:
                print(f"Stale demo artifact: {path.relative_to(ROOT)}")
                return 1
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(value, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
