"""Export P2's offline OpenAPI schemas and the TS types consumed by the mock UI.

No web app import or external generator is needed. --check verifies committed
outputs match the Python models; unsupported schema constructs fail explicitly.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from ra_agent.contracts.core_v1 import (
    EffectivePermission,
    GatewayDecision,
    TaskContractV2,
)
from ra_agent.events import BehaviorEvent

ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = ROOT / "docs/interfaces/schemas/p2-events.openapi.json"
TS_PATH = ROOT / "frontend/src/features/core/generated.ts"
FIXTURE_PATH = ROOT / "tests/fixtures/core/behavior_events.json"
UI_FIXTURE_PATH = ROOT / "frontend/src/features/core/mock/events.json"


def typescript(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(typescript(part) for part in schema["anyOf"])
    kind = schema.get("type")
    if kind in {"string", "boolean", "null"}:
        return kind
    if kind in {"integer", "number"}:
        return "number"
    if kind == "array":
        return f"Array<{typescript(schema['items'])}>"
    if kind == "object":
        properties = schema.get("properties")
        if properties is not None:
            required = schema.get("required", [])
            fields = [
                f"  {name}{'' if name in required else '?'}: {typescript(field)}"
                for name, field in properties.items()
            ]
            return "{\n" + "\n".join(fields) + "\n}"
        extra = schema.get("additionalProperties", {})
        return f"Record<string, {typescript(extra) if isinstance(extra, dict) else 'unknown'}>"
    if not schema:
        return "unknown"
    raise ValueError(f"Unsupported TypeScript schema: {schema}")


def artifacts() -> dict[Path, str]:
    components: dict[str, Any] = {}
    for model in (BehaviorEvent, TaskContractV2, EffectivePermission, GatewayDecision):
        schema = model.model_json_schema(ref_template="#/components/schemas/{model}")
        for name, definition in schema.pop("$defs", {}).items():
            if name in components and components[name] != definition:
                raise ValueError(f"Conflicting component: {name}")
            components[name] = definition
        components[model.__name__] = schema
    spec = {
        "openapi": "3.1.0",
        "info": {
            "title": "P2 Core event and UI contract proposal",
            "version": "1.0",
            "description": "Core event schemas; the task-events route is implemented in PR2.",
        },
        "paths": {
            "/api/v1/tasks/{task_id}/events": {
                "get": {
                    "operationId": "listCoreTaskEvents",
                    "x-implementation-status": "implemented-pr2",
                    "parameters": [
                        {
                            "name": "task_id",
                            "in": "path",
                            "required": True,
                            "schema": {"type": "string"},
                        }
                    ],
                    "responses": {
                        "200": {
                            "description": "APIResponse containing task events in sequence order",
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "type": "object",
                                        "required": ["data"],
                                        "properties": {
                                            "data": {
                                                "type": "array",
                                                "items": {"$ref": "#/components/schemas/BehaviorEvent"},
                                            },
                                            "error": {"type": ["object", "null"]},
                                        },
                                    }
                                }
                            },
                        }
                    },
                }
            }
        },
        "components": {"schemas": components},
    }
    generated = (
        (
            "// Generated by scripts/export_core_event_contracts.py from P2 OpenAPI schemas.\n"
            "// Do not edit by hand. Runtime validation remains on the service boundary.\n\n"
        )
        + "\n\n".join(
            f"export type {name} = {typescript(schema)}"
            for name, schema in sorted(components.items())
        )
        + "\n"
    )
    events = [
        BehaviorEvent.model_validate(event).model_dump(mode="json")
        for event in json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))
    ]
    return {
        SPEC_PATH: json.dumps(spec, ensure_ascii=False, indent=2) + "\n",
        TS_PATH: generated,
        UI_FIXTURE_PATH: json.dumps(events, ensure_ascii=False, indent=2) + "\n",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, content in artifacts().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale:
        print("Outdated generated files: " + ", ".join(stale))
        return 1
    print("P2 OpenAPI, TypeScript and fixture files are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
