from enum import StrEnum


class RiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    FORBIDDEN = "FORBIDDEN"


class PolicyDecision(StrEnum):
    FAST_EXECUTE = "FAST_EXECUTE"
    SANDBOX_CHECK = "SANDBOX_CHECK"
    REQUEST_APPROVAL = "REQUEST_APPROVAL"
    BLOCK = "BLOCK"


class SourceType(StrEnum):
    USER = "user"
    AGENT = "agent"
    EXTERNAL_DOCUMENT = "external_document"
    TOOL_OUTPUT = "tool_output"


class PermissionStatus(StrEnum):
    GRANTED = "GRANTED"
    DENIED = "DENIED"
    PENDING = "PENDING"
    NOT_REQUIRED = "NOT_REQUIRED"
    EXPIRED = "EXPIRED"


class ApprovalStatus(StrEnum):
    PENDING = "PENDING"
    GRANTED = "GRANTED"
    DENIED = "DENIED"
    EXPIRED = "EXPIRED"


class ExecutionStatus(StrEnum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    PENDING_COMMIT = "PENDING_COMMIT"
    BLOCKED = "BLOCKED"
    ROLLED_BACK = "ROLLED_BACK"
    COMMITTED = "COMMITTED"
    CANCELLED = "CANCELLED"
    TIMEOUT = "TIMEOUT"
    WAITING_APPROVAL = "WAITING_APPROVAL"


class StepStatus(StrEnum):
    PLANNED = "PLANNED"
    RISK_CLASSIFYING = "RISK_CLASSIFYING"
    WAITING_PERMISSION = "WAITING_PERMISSION"
    READY = "READY"
    CHECKPOINT_CREATING = "CHECKPOINT_CREATING"
    EXECUTING_FAST = "EXECUTING_FAST"
    EXECUTING_SANDBOX = "EXECUTING_SANDBOX"
    SAFETY_CHECKING = "SAFETY_CHECKING"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    COMMITTING = "COMMITTING"
    ROLLING_BACK = "ROLLING_BACK"
    COMMITTED = "COMMITTED"
    ROLLED_BACK = "ROLLED_BACK"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class RecoverabilityType(StrEnum):
    ATOMIC = "ATOMIC"
    BACKUP_RESTORE = "BACKUP_RESTORE"
    COMPENSATING = "COMPENSATING"
    NON_REVERSIBLE = "NON_REVERSIBLE"


class PermissionType(StrEnum):
    FILE_LIST = "FILE_LIST"
    FILE_READ = "FILE_READ"
    FILE_WRITE = "FILE_WRITE"
    FILE_DELETE = "FILE_DELETE"
    SENSITIVE_READ = "SENSITIVE_READ"
    SHELL_EXEC = "SHELL_EXEC"
    NETWORK_DOWNLOAD = "NETWORK_DOWNLOAD"
    NETWORK_UPLOAD = "NETWORK_UPLOAD"
    MEMORY_READ = "MEMORY_READ"
    MEMORY_WRITE = "MEMORY_WRITE"
    SYSTEM_MODIFY = "SYSTEM_MODIFY"


class MemoryStatus(StrEnum):
    PENDING = "PENDING"
    TRUSTED = "TRUSTED"
    REJECTED = "REJECTED"
    ROLLED_BACK = "ROLLED_BACK"


class ExperimentMode(StrEnum):
    BASELINE = "BASELINE"
    FULL_GUARD = "FULL_GUARD"
    ADAPTIVE_RUNTIME = "ADAPTIVE_RUNTIME"


class AuditEventType(StrEnum):
    TASK_CREATED = "TASK_CREATED"
    PLAN_CREATED = "PLAN_CREATED"
    TOOL_REQUESTED = "TOOL_REQUESTED"
    RISK_CLASSIFIED = "RISK_CLASSIFIED"
    PERMISSION_CHECKED = "PERMISSION_CHECKED"
    APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
    APPROVAL_GRANTED = "APPROVAL_GRANTED"
    APPROVAL_DENIED = "APPROVAL_DENIED"
    CHECKPOINT_CREATED = "CHECKPOINT_CREATED"
    EXECUTION_STARTED = "EXECUTION_STARTED"
    EXECUTION_FINISHED = "EXECUTION_FINISHED"
    DEEP_CHECK_STARTED = "DEEP_CHECK_STARTED"
    DEEP_CHECK_FINISHED = "DEEP_CHECK_FINISHED"
    COMMIT_STARTED = "COMMIT_STARTED"
    COMMIT_FINISHED = "COMMIT_FINISHED"
    ROLLBACK_STARTED = "ROLLBACK_STARTED"
    ROLLBACK_FINISHED = "ROLLBACK_FINISHED"
    TOOL_BLOCKED = "TOOL_BLOCKED"
    STEP_FAILED = "STEP_FAILED"
    TASK_FINISHED = "TASK_FINISHED"
    TASK_CANCELLED = "TASK_CANCELLED"
