from ra_agent.contracts import PermissionType, RecoverabilityType, RiskLevel, ToolSpec

DEFAULT_TOOL_SPECS = (
    ToolSpec(
        name="list_dir",
        description="List entries under an allowed workspace directory",
        required_permissions=[PermissionType.FILE_LIST],
        base_risk=RiskLevel.LOW,
        side_effect_type="NONE",
        reversibility=RecoverabilityType.ATOMIC,
        sandbox_mode="NONE",
        timeout_seconds=5,
        network_required=False,
        supports_dry_run=True,
    ),
    ToolSpec(
        name="read_file",
        description="Read an allowed workspace file",
        required_permissions=[PermissionType.FILE_READ],
        base_risk=RiskLevel.LOW,
        side_effect_type="READ",
        reversibility=RecoverabilityType.ATOMIC,
        sandbox_mode="NONE",
        timeout_seconds=10,
        network_required=False,
        supports_dry_run=True,
    ),
    ToolSpec(
        name="write_file",
        description="Write a pending workspace file",
        required_permissions=[PermissionType.FILE_WRITE],
        base_risk=RiskLevel.MEDIUM,
        side_effect_type="WRITE",
        reversibility=RecoverabilityType.BACKUP_RESTORE,
        sandbox_mode="PENDING",
        timeout_seconds=10,
        network_required=False,
        supports_dry_run=True,
    ),
    ToolSpec(
        name="delete_file",
        description="Delete an allowed workspace file after approval",
        required_permissions=[PermissionType.FILE_DELETE],
        base_risk=RiskLevel.HIGH,
        side_effect_type="DELETE",
        reversibility=RecoverabilityType.BACKUP_RESTORE,
        sandbox_mode="PENDING",
        timeout_seconds=10,
        network_required=False,
        supports_dry_run=True,
    ),
    ToolSpec(
        name="run_shell",
        description="Run an allowlisted process without a shell interpreter",
        required_permissions=[PermissionType.SHELL_EXEC],
        base_risk=RiskLevel.HIGH,
        side_effect_type="PROCESS",
        reversibility=RecoverabilityType.NON_REVERSIBLE,
        sandbox_mode="RESTRICTED",
        timeout_seconds=15,
        network_required=False,
        supports_dry_run=True,
    ),
    ToolSpec(
        name="download_url",
        description="Download a URL into quarantine",
        required_permissions=[PermissionType.NETWORK_DOWNLOAD, PermissionType.FILE_WRITE],
        base_risk=RiskLevel.MEDIUM,
        side_effect_type="WRITE",
        reversibility=RecoverabilityType.ATOMIC,
        sandbox_mode="QUARANTINE",
        timeout_seconds=30,
        network_required=True,
        supports_dry_run=True,
    ),
    ToolSpec(
        name="memory_read",
        description="Read trusted runtime memory",
        required_permissions=[PermissionType.MEMORY_READ],
        base_risk=RiskLevel.LOW,
        side_effect_type="READ",
        reversibility=RecoverabilityType.ATOMIC,
        sandbox_mode="NONE",
        timeout_seconds=5,
        network_required=False,
        supports_dry_run=True,
    ),
    ToolSpec(
        name="memory_write",
        description="Write pending runtime memory",
        required_permissions=[PermissionType.MEMORY_WRITE],
        base_risk=RiskLevel.MEDIUM,
        side_effect_type="WRITE",
        reversibility=RecoverabilityType.ATOMIC,
        sandbox_mode="PENDING",
        timeout_seconds=5,
        network_required=False,
        supports_dry_run=True,
    ),
    ToolSpec(
        name="send_email_dry_run",
        description="Create a pending egress record without sending email",
        required_permissions=[PermissionType.NETWORK_UPLOAD],
        base_risk=RiskLevel.LOW,
        side_effect_type="EGRESS_DRY_RUN",
        reversibility=RecoverabilityType.ATOMIC,
        sandbox_mode="PENDING_EGRESS",
        timeout_seconds=5,
        network_required=False,
        supports_dry_run=True,
    ),
)

TOOL_NAMES = tuple(spec.name for spec in DEFAULT_TOOL_SPECS)
